"""empty message

Revision ID: 006faf94d789
Revises: cd096a6eb5df
Create Date: 2020-03-21 16:37:55.070924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006faf94d789'
down_revision = 'cd096a6eb5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('artist_location_lat', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('artist_location_long', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'page', ['Page_Id'], ['id'])
    op.drop_column('reward', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'user', ['creator_id'], ['id'])
    op.drop_column('page', 'artist_location_long')
    op.drop_column('page', 'artist_location_lat')
    # ### end Alembic commands ###
