"""empty message

Revision ID: 32f3405628f3
Revises: cc6265aecfc4
Create Date: 2020-03-22 11:22:09.845325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f3405628f3'
down_revision = 'cc6265aecfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'page', ['Page_Id'], ['id'])
    op.drop_column('reward', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
