"""empty message

Revision ID: 8e3bcdb8436a
Revises: 006faf94d789
Create Date: 2020-03-21 19:39:45.274477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3bcdb8436a'
down_revision = '006faf94d789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'page', ['Page_Id'], ['id'])
    op.drop_column('reward', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
