"""empty message

Revision ID: cd096a6eb5df
Revises: 53d2d5929885
Create Date: 2020-03-21 12:24:10.853833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd096a6eb5df'
down_revision = '53d2d5929885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('artist_category', sa.String(), nullable=True))
    op.add_column('page', sa.Column('artist_job', sa.String(), nullable=True))
    op.add_column('page', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('page', sa.Column('description_crisis', sa.String(), nullable=True))
    op.add_column('page', sa.Column('description_general', sa.String(), nullable=True))
    op.add_column('page', sa.Column('description_rewards', sa.String(), nullable=True))
    op.add_column('page', sa.Column('description_title', sa.String(), nullable=True))
    op.add_column('page', sa.Column('media_path', sa.String(), nullable=True))
    op.add_column('page', sa.Column('titlepicture_path', sa.String(), nullable=True))
    op.add_column('reward', sa.Column('Page_Id', sa.Integer(), nullable=True))
    op.add_column('reward', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('reward', sa.Column('category_form', sa.String(), nullable=True))
    op.add_column('reward', sa.Column('category_time', sa.String(), nullable=True))
    op.add_column('reward', sa.Column('description', sa.String(), nullable=True))
    op.add_column('reward', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('reward', sa.Column('primary', sa.Boolean(), nullable=True))
    op.add_column('reward', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'page', ['Page_Id'], ['id'])
    op.drop_column('reward', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('creator_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reward', type_='foreignkey')
    op.create_foreign_key(None, 'reward', 'user', ['creator_id'], ['id'])
    op.drop_column('reward', 'title')
    op.drop_column('reward', 'primary')
    op.drop_column('reward', 'price')
    op.drop_column('reward', 'description')
    op.drop_column('reward', 'category_time')
    op.drop_column('reward', 'category_form')
    op.drop_column('reward', 'active')
    op.drop_column('reward', 'Page_Id')
    op.drop_column('page', 'titlepicture_path')
    op.drop_column('page', 'media_path')
    op.drop_column('page', 'description_title')
    op.drop_column('page', 'description_rewards')
    op.drop_column('page', 'description_general')
    op.drop_column('page', 'description_crisis')
    op.drop_column('page', 'artist_name')
    op.drop_column('page', 'artist_job')
    op.drop_column('page', 'artist_category')
    # ### end Alembic commands ###
